
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String[] userName = new String[10];
    String[] password = new String[10];
    int arraySize = 0;
    int customerIndex = 0;
    
    
    
    public LoginForm() {
        initComponents();
    }
    
    public LoginForm(RegisterWindow []customerData) {
        initComponents();
        
        this.userName[arraySize] = customerData[arraySize].username;
        this.password[arraySize] = customerData[arraySize].password;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        Footer = new javax.swing.JPanel();
        signUpDirect = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(153, 0, 0));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0, 17, 0, 17, 0};
        Header.setLayout(jPanel1Layout);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Welcome to LongNugget");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.6;
        Header.add(jLabel1, gridBagConstraints);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Body.setBackground(new java.awt.Color(153, 0, 0));
        Body.setMinimumSize(new java.awt.Dimension(334, 60));
        Body.setPreferredSize(new java.awt.Dimension(334, 60));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 76, 0, 76, 0};
        jPanel2Layout.rowHeights = new int[] {0, 1, 0, 1, 0};
        jPanel2Layout.columnWeights = new double[] {50.0, 0.0};
        jPanel2Layout.rowWeights = new double[] {0.0};
        Body.setLayout(jPanel2Layout);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        Body.add(jLabel2, gridBagConstraints);

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        Body.add(userNameField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Body.add(jLabel3, gridBagConstraints);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 40;
        Body.add(passwordField, gridBagConstraints);

        getContentPane().add(Body, java.awt.BorderLayout.CENTER);

        Footer.setBackground(new java.awt.Color(153, 0, 0));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0};
        jPanel3Layout.rowHeights = new int[] {0, 18, 0, 18, 0, 18, 0, 18, 0};
        Footer.setLayout(jPanel3Layout);

        signUpDirect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signUpDirect.setForeground(new java.awt.Color(255, 204, 51));
        signUpDirect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpDirect.setText("Don’t have account? Click here!");
        signUpDirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpDirectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signUpDirectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signUpDirectMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        Footer.add(signUpDirect, gridBagConstraints);

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 10;
        Footer.add(loginButton, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Copyright by LN17-2");
        jLabel5.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        Footer.add(jLabel5, gridBagConstraints);

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(616, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int checkUsernameList(String username){
        int customerIndex = 0;
        for(int i = 0 ; i <= arraySize ;i++){
            if(username.equals(userName[i])){
                this.customerIndex = customerIndex;
                return customerIndex;
            }
        }
        return -1;
    }
    
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void signUpDirectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpDirectMouseEntered
       signUpDirect.setForeground(Color.blue);
    }//GEN-LAST:event_signUpDirectMouseEntered

    private void signUpDirectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpDirectMouseExited
        Color yellowNugget = new Color(255,204,51);
        signUpDirect.setForeground(yellowNugget);
    }//GEN-LAST:event_signUpDirectMouseExited

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
//        if(userNameField.getText().isEmpty()){
//              JOptionPane.showMessageDialog(null, "Username must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(passwordField.getText().isEmpty()){
//             JOptionPane.showMessageDialog(null, "Password must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(checkUsernameList(userNameField.getText()) == -1 || !passwordField.getText().equals(password[customerIndex])){
//            JOptionPane.showMessageDialog(null, "Username or password is invalid!", "Error", JOptionPane.ERROR_MESSAGE);     
//        }
//        else{
            //new VideoForm().setVisible(true);

            MainForm mf = new MainForm();
            mf.show();
            this.dispose();
            
            //new CartForm().setVisible(true);
            //new VideoForm().setVisible(true);
        //}
        
       
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signUpDirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpDirectMouseClicked
        RegisterWindow rw = new RegisterWindow();
        rw.show();
        this.dispose();
    }//GEN-LAST:event_signUpDirectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signUpDirect;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
