
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus-gl553vd
 */

public class RegisterWindow extends javax.swing.JFrame {

    String username;
    String password;
    String email;
    String gender;
    String phone;
    String address;
    
    int i = 0;
    
    RegisterWindow[] customerData = new RegisterWindow[10];
    
   
    
    public RegisterWindow(){
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        genderGroup = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        RegisterLbl = new javax.swing.JLabel();
        Fields = new javax.swing.JPanel();
        Forms = new javax.swing.JPanel();
        formLbl1 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        formLbl2 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        formLbl3 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        formLbl4 = new javax.swing.JLabel();
        confPasswordTxt = new javax.swing.JPasswordField();
        formLbl5 = new javax.swing.JLabel();
        genderPnl = new javax.swing.JPanel();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        formLbl6 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        formLbl7 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        Buttons = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        RegisterBtn = new javax.swing.JButton();
        Footer = new javax.swing.JPanel();
        CopyLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(153, 0, 0));
        java.awt.GridBagLayout HeaderLayout = new java.awt.GridBagLayout();
        HeaderLayout.columnWidths = new int[] {0};
        HeaderLayout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        Header.setLayout(HeaderLayout);

        RegisterLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        RegisterLbl.setForeground(new java.awt.Color(255, 204, 51));
        RegisterLbl.setText("Register");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        Header.add(RegisterLbl, gridBagConstraints);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Fields.setBackground(new java.awt.Color(153, 0, 0));
        Fields.setLayout(new java.awt.BorderLayout());

        Forms.setBackground(new java.awt.Color(153, 0, 0));
        java.awt.GridBagLayout FormsLayout = new java.awt.GridBagLayout();
        FormsLayout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        FormsLayout.rowHeights = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        FormsLayout.columnWeights = new double[] {0.0};
        FormsLayout.rowWeights = new double[] {0.0};
        Forms.setLayout(FormsLayout);

        formLbl1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl1.setForeground(new java.awt.Color(255, 204, 51));
        formLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 10;
        Forms.add(usernameTxt, gridBagConstraints);

        formLbl2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl2.setForeground(new java.awt.Color(255, 204, 51));
        formLbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl2.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 10;
        Forms.add(emailTxt, gridBagConstraints);

        formLbl3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl3.setForeground(new java.awt.Color(255, 204, 51));
        formLbl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl3.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 10;
        Forms.add(passwordTxt, gridBagConstraints);

        formLbl4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl4.setForeground(new java.awt.Color(255, 204, 51));
        formLbl4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl4.setText("Confirm Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 10;
        Forms.add(confPasswordTxt, gridBagConstraints);

        formLbl5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl5.setForeground(new java.awt.Color(255, 204, 51));
        formLbl5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl5.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl5, gridBagConstraints);

        genderPnl.setBackground(new java.awt.Color(153, 0, 0));

        maleBtn.setBackground(new java.awt.Color(153, 0, 0));
        genderGroup.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        maleBtn.setForeground(new java.awt.Color(255, 204, 51));
        maleBtn.setText("Male");
        genderPnl.add(maleBtn);

        femaleBtn.setBackground(new java.awt.Color(153, 0, 0));
        genderGroup.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        femaleBtn.setForeground(new java.awt.Color(255, 204, 51));
        femaleBtn.setText("Female");
        genderPnl.add(femaleBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        Forms.add(genderPnl, gridBagConstraints);

        formLbl6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl6.setForeground(new java.awt.Color(255, 204, 51));
        formLbl6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl6.setText("Phone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 10;
        Forms.add(phoneTxt, gridBagConstraints);

        formLbl7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        formLbl7.setForeground(new java.awt.Color(255, 204, 51));
        formLbl7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formLbl7.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Forms.add(formLbl7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.ipady = 10;
        Forms.add(addressTxt, gridBagConstraints);

        Fields.add(Forms, java.awt.BorderLayout.CENTER);

        Buttons.setBackground(new java.awt.Color(153, 0, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10);
        flowLayout1.setAlignOnBaseline(true);
        Buttons.setLayout(flowLayout1);

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        Buttons.add(BackBtn);

        ResetBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        Buttons.add(ResetBtn);

        RegisterBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        Buttons.add(RegisterBtn);

        Fields.add(Buttons, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Fields, java.awt.BorderLayout.CENTER);

        Footer.setBackground(new java.awt.Color(153, 0, 0));
        java.awt.GridBagLayout FooterLayout = new java.awt.GridBagLayout();
        FooterLayout.columnWidths = new int[] {0};
        FooterLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        Footer.setLayout(FooterLayout);

        CopyLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        CopyLbl.setForeground(new java.awt.Color(255, 204, 51));
        CopyLbl.setText("Copyright by LN17-2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        Footer.add(CopyLbl, gridBagConstraints);

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(551, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public boolean checkNumeric(){
        for(int i = 0 ; i<phoneTxt.getText().length();i++){
            if(!Character.isDigit(phoneTxt.getText().charAt(i))){
                return false;
            }
        }
        return true;
    }
    public boolean checkAlphaNum(){
        boolean a = false;
        boolean b = false;

        for(int i = 0; i<passwordTxt.getText().length(); i++){ 
            if(Character.isAlphabetic(passwordTxt.getText().charAt(i))){
                a = true;
            }
            if(Character.isDigit(passwordTxt.getText().charAt(i))){
                b = true;
            }
            if((a && b) == true){
                return true;
            }            
        }
        return false;
    }
    
    public boolean checkUsername(){
        if(usernameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(usernameTxt.getText().length() <= 3){
            JOptionPane.showMessageDialog(null, "Username must be more than 3 characters!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else {
            customerData[i] = new RegisterWindow();
            customerData[i].username = usernameTxt.getText();
            return true;
        }
    }
    public boolean checkEmail(){
        if(emailTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Email must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailTxt.getText())))
        {
            JOptionPane.showMessageDialog(null, "Email must be valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{ 
            customerData[i].email = emailTxt.getText();
            return true;
        
        }
        
    } 
    public boolean checkPassword(){
        if(passwordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!checkAlphaNum()){
            JOptionPane.showMessageDialog(null, "Password must be alphanumeric!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else return true;
    }
    public boolean checkConfPassword(){
        if(confPasswordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Confirm Password must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!confPasswordTxt.getText().equals(passwordTxt.getText())){
            JOptionPane.showMessageDialog(null, "Confirm Password must be equals to Password!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{
            customerData[i].password = confPasswordTxt.getText();
            return true;
        } 
    }
    public boolean checkGender(){
        if(!femaleBtn.isSelected() && !maleBtn.isSelected()){
            JOptionPane.showMessageDialog(null, "Gender must be selected!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else {
            if(femaleBtn.isSelected())
                customerData[i].gender = femaleBtn.getText();
            else
                customerData[i].gender = maleBtn.getText();
            return true;
        }
    }
    public boolean checkPhone(){
        if(phoneTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Phone Number must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!checkNumeric()){
            JOptionPane.showMessageDialog(null, "Phone Number must be Numeric!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else{ 
            customerData[i].phone = phoneTxt.getText();
            return true;
        }
        
    }
    public boolean checkAddress(){
        if(addressTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Address must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(addressTxt.getText().length() <= 8){
            JOptionPane.showMessageDialog(null, "Address must be more than 8 characters!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else {
            customerData[i].address = addressTxt.getText();
            return true;
        }
    }
    
    //Displays Login 
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        i = 0;
        customerData = null;
        LoginForm lf = new LoginForm();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed
    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
         int n = JOptionPane.showConfirmDialog(null, "Are you sure you want to reset?", "Reset Option", JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION){
            usernameTxt.setText("");
            emailTxt.setText("");
            passwordTxt.setText("");
            confPasswordTxt.setText("");
            genderGroup.clearSelection();
            phoneTxt.setText("");
            addressTxt.setText("");
        }else{
            System.out.println("Reset cancelled.");
        }
        
    }//GEN-LAST:event_ResetBtnActionPerformed
    
    //Add save registered data and redirect to login form
    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        if(
                checkUsername()&&
                checkEmail() &&
                checkPassword() &&
                checkConfPassword() &&
                checkGender() &&
                checkPhone()&&
                checkAddress()
                ){

            i++;
            
            JOptionPane.showMessageDialog(null, "Success register account");
            
            new LoginForm(customerData).setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new RegisterWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JPanel Buttons;
    private javax.swing.JLabel CopyLbl;
    private javax.swing.JPanel Fields;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Forms;
    private javax.swing.JPanel Header;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JLabel RegisterLbl;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JPasswordField confPasswordTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JLabel formLbl1;
    private javax.swing.JLabel formLbl2;
    private javax.swing.JLabel formLbl3;
    private javax.swing.JLabel formLbl4;
    private javax.swing.JLabel formLbl5;
    private javax.swing.JLabel formLbl6;
    private javax.swing.JLabel formLbl7;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JPanel genderPnl;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
